// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfore7yET1CpPC5yQ8D6fJucmyCnk4JU',
    appId: '1:459043003062:web:bc9e50731fe73d0ec9a417',
    messagingSenderId: '459043003062',
    projectId: 'ulala-now2',
    authDomain: 'ulala-now2.firebaseapp.com',
    storageBucket: 'ulala-now2.firebasestorage.app',
    measurementId: 'G-LM7SB3W97G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJOrIdbWb7Gg78f56tBBnJN-snpH2CIg',
    appId: '1:459043003062:android:6109ac296c044ca9c9a417',
    messagingSenderId: '459043003062',
    projectId: 'ulala-now2',
    storageBucket: 'ulala-now2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVfore7yET1CpPC5yQ8D6fJucmyCnk4JU',
    appId: '1:459043003062:web:b4c59e30619a1344c9a417',
    messagingSenderId: '459043003062',
    projectId: 'ulala-now2',
    authDomain: 'ulala-now2.firebaseapp.com',
    storageBucket: 'ulala-now2.firebasestorage.app',
    measurementId: 'G-EW92LK9XGC',
  );
}
